# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rmbg.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rmbg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrmbg.proto\x12\x04rmbg\"-\n\x17RemoveBackgroundRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\".\n\x18RemoveBackgroundResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x32`\n\x0bRmbgService\x12Q\n\x10RemoveBackground\x12\x1d.rmbg.RemoveBackgroundRequest\x1a\x1e.rmbg.RemoveBackgroundResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rmbg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REMOVEBACKGROUNDREQUEST']._serialized_start=20
  _globals['_REMOVEBACKGROUNDREQUEST']._serialized_end=65
  _globals['_REMOVEBACKGROUNDRESPONSE']._serialized_start=67
  _globals['_REMOVEBACKGROUNDRESPONSE']._serialized_end=113
  _globals['_RMBGSERVICE']._serialized_start=115
  _globals['_RMBGSERVICE']._serialized_end=211
# @@protoc_insertion_point(module_scope)
