name: CI Full

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  full-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Cache Turbo and node modules
        uses: actions/cache@v4
        with:
          path: |
            .turbo
            node_modules
          key: turbo-cache-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            turbo-cache-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run full checks (build, typecheck, lint, tests)
        run: pnpm run check

      - name: Run tests with coverage
        run: pnpm -w -r exec vitest --run --coverage

      - name: Upload test & coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-and-tests
          path: |
            **/coverage/**
            **/test-results/**
